### ISSUE TITLE
Make another bot

### ISSUE THREAD

**Issue by xmha97** [radinshayanfar/RJBot#2]
سلام، نمی‌دونم این بات توسط شما هاست میشد یا نه اما توسط تلگرام مسدود شده! اگه بات مشابهی میشناسید، لطفا معرفی کنید.
![Screenshot_2022-03-03-07-44-39-869_org.telegram.messenger.web.jpg](https://user-images.githubusercontent.com/23485114/156495472-6f2c8c50-f8cf-4c0c-8037-548a450c74cc.jpg)

**Comment by radinshayanfar** [comment]
Hi!
Unfortunately, the bot isn't hosted publicly anywhere by me. However, the installation process is very straightforward with the provided script. Feel free to host it for yourself under [GPL3 license](https://github.com/radinshayanfar/RJBot/blob/master/LICENSE).
